### PR TITLE
Add data engineer roadmap

### PR DESCRIPTION
**Pull request by SartMorgs**
#### What roadmap does this PR target?

- [ ] Code Change
- [ ] Frontend Roadmap
- [ ] Backend Roadmap
- [ ] DevOps Roadmap
- [ ] All Roadmaps
- [x] New Roadmap
- [x] Data Engineer Roadmap
- [ ] Guides

#### Please acknowledge the items listed below

- [ ] I have discussed this contribution and got a go-ahead in an issue before opening this pull request.
- [x] This is not a duplicate issue. I have searched and there is no existing issue for this.
- [x] I understand that these roadmaps are highly opinionated. The purpose is to not to include everything out there in these roadmaps but to have everything that is most relevant today comparing to the other options listed.
- [x] I have read the [contribution docs](../contributing) before opening this PR.

#### Enter the details about the contribution

In this roadmap I included de first and most important concepts, tools and skills to start with data engineering.

### CODE REVIEW

**Comment by chrisfinlayson** [comment]
Hi - i'd like to collaborate on this PR ass I have a number of additions.

**Comment by SartMorgs** [comment]
Hi chrisfinlayson!! Of course I would like. Let me know about what you are thinking. How would it be? The balsamiq flow diagram... Do you want to use some framework for this?

**Comment by chrisfinlayson** [comment]
So I think fleshing out the various tools, methods, patterns etc would be the first stage

Then drawing out the diagram in balsamiq can come after.

I have a development branch, forked from yours and already made some updates.  Can you allow me access to your repo so that I can merge changes into the PR

Of course, have a look first.   Happy to do all over email or jump onto a quick zoom call - up to you!

Thanks! Would be great to collaborate.

**Comment by SartMorgs** [comment]
I sent a invitation for you. We can talk by email for while :)
You can take it at my profile on github, email me.

**Comment by chrisfinlayson** [comment]
Great - thank you!  Have accepted and will push the changes I prepared earlier for you to review!

Have a great weekend

**Pull request closed without merging**
